### ISSUE TITLE
eslintrc breaks eslint in atom on Windows

### ISSUE THREAD

**Issue by aggieben** [nathanboktae/mocha-phantomjs-core#15]
![image](https://cloud.githubusercontent.com/assets/1321/11728492/d334450a-9f4f-11e5-8231-2da8979e2b6c.png)

I don't know if being a) in Atom or b) on Windows matters at all, but the `.eslintrc` really makes my Atom setup unhappy.

**Comment by nathanboktae** [comment]
You probably have an outdated version of eslint. It had some breaking changes fro. Pre-1.0.
