### ISSUE TITLE
Could the npm package not bundle the PhantomJS binary?

### ISSUE THREAD

**Issue by mislav** [nathanboktae/mocha-phantomjs-core#18]
Right now it seems that a 17MB `phantomjs` binary is shipped with the npm module. Could it not? The whole reason I wanted to switch to this npm package is because `mocha-phantomjs` has a dependency on the `phantomjs` module, and that opens a whole can of worms re: repeated and redundant PhantomJS installs.

Can I just be responsible for installing/upgrading my own version of PhantomJS?

**Comment by nathanboktae** [comment]
> Right now it seems that a 17MB phantomjs binary is shipped with the npm module.

No this project has [no dependencies](https://github.com/nathanboktae/mocha-phantomjs-core/blob/master/package.json), the whole reason it was extracted from `mocha-phantomjs-core`. What makes you think it is including the phantomjs binary?

**Comment by mislav** [comment]
It's the phantomjs binary that mostly makes me think that this package includes the phantomjs binary:

```
$ cat package.json
{ "devDependencies": { "mocha-phantomjs-core": "2.0.0" } }

$ rm -rf ./node_modules

$ npm install
/private/tmp/mocha-test
└── mocha-phantomjs-core@2.0.0

npm WARN mocha-test No description
npm WARN mocha-test No repository field.
npm WARN mocha-test No license field.

$ ls -lh node_modules/mocha-phantomjs-core/phantomjs
-rwxr-xr-x  1 mislav  wheel    50M Feb  4 05:27 node_modules/mocha-phantomjs-core/phantomjs

$ file node_modules/mocha-phantomjs-core/phantomjs
node_modules/mocha-phantomjs-core/phantomjs: Mach-O 64-bit executable x86_64
```

It's 17MB when gzipped:

```
$ tar -cz ./node_modules | wc -c
 17674240
```

Seems like the version is tad outdated:

```
$ ./node_modules/mocha-phantomjs-core/phantomjs -v
2.0.0
```

**Comment by nathanboktae** [comment]
WAT I have this explicitly in [.npmignore](https://github.com/nathanboktae/mocha-phantomjs-core/blob/79073f862fc3a508f06e982897ec702150b13ab4/.npmignore#L7-L8) ...

**Comment by nathanboktae** [comment]
Thanks for reporting. `2.0.1` doesn't have the binary now.

**Comment by mislav** [comment]
Thanks for the quick update, Nathan!
