### ISSUE TITLE
`mocha.run() was called with no tests` - html testrunner with multiple script inclusions

### ISSUE THREAD

**Issue by rosskevin** [nathanboktae/mocha-phantomjs-core#21]
`mocha.run() was called with no tests`

Repo: https://github.com/alienfast/picker.js

I'm having a hard time setting up my suite.  I'm expecting one html file and many js suite files.  It isn't feasible to include all tests inside the html as the example shows.

You can run this with structure with standard mocha, is there a reason this isn't working for me with `mocha-phantomjs-core`?

**Command**
`node_modules/.bin/phantomjs node_modules/mocha-phantomjs-core/mocha-phantomjs-core.js file:///Users/kross/projects/picker.js/test/testrunner.html`

**html**

``` html
<!DOCTYPE html>
<html>
<head>
  <title>Mocha</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  <link rel="stylesheet" href="../node_modules/mocha/mocha.css" />

  <!-- jquery -->
  <script src="../node_modules/jquery/dist/jquery.min.js"></script>
  <script src="../dist/picker.js.iife.js"></script>

</head>
<body>

<div id="mocha"></div>

<!-- Test input form -->
<h2>Test input</h2>
<form>
  <input type="text" class="form-control">
</form>


<script src="../node_modules/mocha/mocha.js"></script>
<script src="../node_modules/chai/chai.js"></script>
<script src="../node_modules/chai-jquery/chai-jquery.js"></script>


<script>mocha.setup('bdd')</script>
<script src="testSetup.js"></script>

<script>
  mocha.checkLeaks();
  mocha.globals(['jQuery']);
  mocha.run()
</script>
</body>
</html>
```

**testSetup.js**

``` javascirpt
var $ = window.jQuery

// non-es6 for quick browser debugging of setup
describe('Test setup', function () {


  it('should be able to jquery find element', () => {
    var $input = $('input')
    if($input.length !== 1){
      console.error('Expected length to be 1 but found', $input)
      throw new Error('Expected length to be 1')
    }
  })
})
```

It seems like I'm missing something simple...ideas?

**Comment by rosskevin** [comment]
yikes, I'm using this through gulp-mocha-phantomjs and looks like I'm on 1.3.0 - I'll try to update.

**Comment by rosskevin** [comment]
Same results with version 2.0.1

**Comment by rosskevin** [comment]
Ok, figured it out.  I thought I had a pure pre-ES2015 test on include, but I still missed an arrow function.  Converting `() =>` to `function()` made it see the test.

With that said, if anyone has any tips for ES2015 tests _with_ phantomjs, please let me know.

**Comment by rosskevin** [comment]
If someone runs into this, I've setup the picker.js project with a test rollup so I can code in ES2015.

See https://github.com/alienfast/picker.js/blob/master/gulpfile.babel.js

**Comment by nathanboktae** [comment]
Yes it's always good practice to do your tests on your final production bundle.

**Comment by rosskevin** [comment]
I think you misunderstand, I was testing the production bundle,  but the tests themselves are written in ES2015 and need transpiled first.  This isn't the case with non-browser mocha (it accepts ES2015) ,  but makes total sense here because it is a browser environment.

**Comment by nathanboktae** [comment]
Ah your tests, yes, but you are also misunderstanding something. It's phantomjs' JavaScript engine that doesn't accept "ES2015" ([the reason for air quotes](http://kangax.github.io/compat-table/es6/)), so it's about the JavaScript environment not any particular library.

However this test below will run fine in Chrome and Firefox, but won't even compile in Node 5 because it doesn't have destructuring assignment (part of ES6 but Node.js is behind on its V8 versions compared to Chrome as of this writing).

``` javascript
describe('Node.js is behind', function() {
  it('wont compile in node 5', function() {
    var [_, x, y] = [1,2,3]
    x.should.equal(2)
  })
})
```

**Comment by rosskevin** [comment]
No,  I understand,  that's why I said it

> makes total sense here because it is a browser environment

Your comment was about my production bundle,  which I was already using,  so I clarified.  In your last comment you just added more info.  

Thanks for the project!

**Comment by nathanboktae** [comment]
No problem, glad to help.

But to be extra clear, It's about the JavaScript Engine it's running on, not if it has a DOM or not. E.g. at my company currently, I write my tests in ES2015 and I don't need to compile them with babel because I only run them in Firefox and Chrome. In fact I can use destructuring assignment in them that I can't in my mocha tests in Node 4.

**Comment by rosskevin** [comment]
It's clear,  I just want them run via command line,  without a complicated setup,  as well as on Travis etc.  Any pointers are welcome if there is something better.

**Comment by kiwenlau** [comment]
In my case, lacking of "describe" in the test file cause the problem:

```js
var should = chai.should();

it("should return 3", function()
{
    var sum = add(1, 2);
    should.equal(sum, 3);
});
```

add "describe" solved the problem：

```js
var should = chai.should();

describe("add", function()
{
	it("should return 3", function()
    {
        var sum = add(1, 2);
        should.equal(sum, 3);
    });
});
```

FYI, the test without "describe" works fine when I run it in chrome other than phantomjs.

In addition, I use mocha-phantomjs, not mocha-phantomjs-core.
