### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by davidhewitt** [nathanboktae/mocha-phantomjs-core#28]
Hi,

This is a really useful library, thanks. I'd like to be able to use callPhantom to change viewportSize in tests. Looks like this feature is newer than the last release on npm (2.0.1?). Is there plans for a newer release?

Cheers
David

**Comment by nathanboktae** [comment]
Sorry about that, I released `2.1.0` just now.

**Comment by davidhewitt** [comment]
Great, thanks very much!
