### ISSUE TITLE
Incorrect Documentation?

### ISSUE THREAD

**Issue by jonny-improbable** [nathanboktae/mocha-phantomjs-core#30]
Sorry for the question, but the documentation in the README implies one can simply:

```
$ npm install mocha-phantomjs-core
$ phantomjs mocha-phantomjs-core.js my-tests.html
```

However if I try to do this I get the following error from phantom:

```
Can't open 'mocha-phantomjs-core.js'
```

I can resolve this by giving phantomjs the relative path to the `mocha-phantomjs-core.js` file, ie:

```
phantomjs ./node_modules/mocha-phantomjs-core/mocha-phantomjs-core.js my-tests.html
```

Should the README be updated to reflect this or am I missing a trick?

**Comment by nathanboktae** [comment]
I added some examples. usually in those usage examples where the binary refers to itself, specifying the location to the binary (or in this case the script) is up to the user. but I'm sure 99.9% of usage is via npm so it's good to add.
