### ISSUE TITLE
open transport timeout

### ISSUE THREAD

**Issue by vercha** [nathanboktae/mocha-phantomjs-core#34]
as running my tests many times, an issue seems relevant to web-socket turns up frequently:

I run test with : phantomjs --web-security=false ./node_modules/mocha-phantom
js-core/mocha-phantomjs-core.js  test/test.html

**Comment by nathanboktae** [comment]
How is this relevant to `mocha-phantomjs-core`? Do your tests pass in a browser? Are you trying to use a websocket functionality that isn't in the version of phantomjs? Did you debug your tests?

**Comment by vercha** [comment]
It pass in chrome browser every time, and always fail with phantomjs.  I did use  websocket in my test with phantomjs V2.1.1 .(It's about P2P chat tests). The error tip shows: 
"open transport timeout".

I have no idea of debugging this issue, thanks for any advice!
