### ISSUE TITLE
PhantomJS 2.5

### ISSUE THREAD

**Issue by enyo** [nathanboktae/mocha-phantomjs-core#35]
Is there a way to get PhantomJS 2.5 with this library?

**Comment by nathanboktae** [comment]
This is a bring-your-own-binary library. npm, wget, brew, whatever it's up to you.

Are you asking instead for a test target for PhantomJS 1.5?

**Comment by enyo** [comment]
I'm sorry, I didn't see my `phantomjs-prebuilt` dependency, and assumed that this library bundled the binary. Thanks for your reply.
