### ISSUE TITLE
Calling `mocha.run()` with no tests should result in an error

### ISSUE THREAD

**Issue by nathanboktae** [nathanboktae/mocha-phantomjs-core#5]
See https://github.com/metaskills/mocha-phantomjs/blob/v4/test/no-tests.html

**Comment by bdunks** [comment]
Hi,

Out of curiosity, can I ask why this should result in an error?

In a typical build workflow, I'll use gulp-mocha-phantomjs, which requires mocha-phantomjs-core ^1.0.0, to continously execute tests as files change.

When I start new project, I generally start with a decent amount of scaffolding I've built from project to project, which includes a gulp file and testing environment, but no tests.

It came as a surprise to me yesterday that gulp wasn't able to complete the build tasks until at least one test has been added to the project.

There are obviously several options to mitigate this issue within a project using mocha-phantomjs, and I'm not indicating that compatibility with gulp-mocha-phantomjs should be this project's concern -- just wondering if I can understand the justification and possibly put the use case on the table for consideration.

Thanks

**Comment by nathanboktae** [comment]
If something caused your tests to not load at all, mocha normally passes with 0 tests ran. A test run with no tests is a big red herring and I've been bitten many times in the past about a successful build that wasn't successful at all because tests failed to run.

If you've added all that scaffolding, add one simple tests for the scaffolding. Or don't enable your test task until you actually write some tests.

**Comment by bdunks** [comment]
Agree that either of the two options you mention are easy ways to avoid this issue -- thanks for clarifying the justification.  Makes sense.
